package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const piMemoryBridgeName = "model-switcher-memory.js"
const piMemoryBridgeMarker = "// ModelSwitcher shared memory bridge"

// Install a user extension so ordinary `pi` invocations also load the vault.
// Read memories per turn rather than copying them into a prompt file: edits and
// deletions take effect without restarting, and .pi/APPEND_SYSTEM.md cannot
// shadow the shared memories. Existing user prompts and settings stay intact.
func ensurePiMemoryBridge() error {
	if _, err := os.Stat(memoryVaultRoot()); errors.Is(err, os.ErrNotExist) {
		return nil
	} else if err != nil {
		return err
	}
	path := filepath.Join(piRoot(), "extensions", piMemoryBridgeName)
	previous, err := os.ReadFile(path)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if info, statErr := os.Lstat(path); statErr == nil {
		if !info.Mode().IsRegular() || !strings.HasPrefix(string(previous), piMemoryBridgeMarker) {
			return errors.New("pi 共享记忆扩展路径已被其他文件占用，未覆盖")
		}
	} else if !errors.Is(statErr, os.ErrNotExist) {
		return statErr
	}
	vault, err := filepath.Abs(memoryVaultRoot())
	if err != nil {
		return err
	}
	vaultJSON, err := json.Marshal(vault)
	if err != nil {
		return err
	}
	source := []byte(strings.ReplaceAll(piMemoryBridgeSource, "__VAULT_PATH__", string(vaultJSON)))
	if bytes.Equal(previous, source) {
		return nil
	}
	if len(previous) > 0 {
		if err := atomicWrite(memoryBackupPath(path, "integration"), previous); err != nil {
			return fmt.Errorf("备份 pi 记忆扩展失败: %w", err)
		}
	}
	return atomicWrite(path, source)
}

// No Pi package imports: this extension works with both package names used by
// Pi, and depends only on the stable before_agent_start extension contract.
const piMemoryBridgeSource = `// ModelSwitcher shared memory bridge
// Generated by ModelSwitcher. Memory contents are read from the vault per turn.
import { readdirSync, openSync, fstatSync, readSync, closeSync } from "node:fs";
import { basename, dirname, join, normalize, resolve } from "node:path";
import { createHash } from "node:crypto";

const vault = __VAULT_PATH__;
const maxBytes = 64 * 1024;
const maxNoteBytes = 16 * 1024;
const start = "<!-- model-switcher:shared-memory:start -->";
const end = "<!-- model-switcher:shared-memory:end -->";

function projectID(directory) {
  const clean = normalize(directory);
  const slug = basename(clean).toLowerCase().replace(/[^a-z0-9._-]+/g, "-").replace(/^[-.]+|[-.]+$/g, "") || "project";
  return slug + "-" + createHash("sha256").update(clean).digest("hex").slice(0, 8);
}

function memoryDirectories(cwd) {
  const projects = [];
  for (let directory = resolve(cwd); ; directory = dirname(directory)) {
    projects.push(join(vault, "projects", projectID(directory)));
    if (dirname(directory) === directory) break;
  }
  return [join(vault, "global"), ...projects.reverse()];
}

function readMemories(cwd) {
  const sections = [];
  let remaining = maxBytes;
  let notes = 0;
  let truncated = false;
  for (const directory of memoryDirectories(cwd)) {
    let files;
    try {
      files = readdirSync(directory, { withFileTypes: true });
    } catch (error) {
      if (error.code === "ENOENT") continue;
      throw error;
    }
    files = files.filter(file => file.isFile() && /\.md$/i.test(file.name) && file.name.toLowerCase() !== "index.md");
    files.sort((a, b) => {
      const priority = name => name.toLowerCase() === "soul.md" ? 0 : 1;
      return priority(a.name) - priority(b.name) || (a.name < b.name ? -1 : a.name > b.name ? 1 : 0);
    });
    for (const file of files) {
      if (remaining <= 0 || notes >= 512) { truncated = true; break; }
      const path = join(directory, file.name);
      let descriptor;
      try {
        descriptor = openSync(path, "r");
        const info = fstatSync(descriptor);
        if (!info.isFile() || info.size === 0) continue;
        const buffer = Buffer.alloc(Math.min(info.size, maxNoteBytes, remaining));
        const length = readSync(descriptor, buffer, 0, buffer.length, 0);
        remaining -= length;
        const content = buffer.subarray(0, length).toString("utf8").replace(/^\uFEFF/, "").trim();
        if (!content) continue;
        notes++;
        const incomplete = info.size > length;
        sections.push("## " + path + "\n\n" + content + (incomplete ? "\n\n[Excerpt; read this file for the complete memory.]" : ""));
        truncated ||= incomplete;
      } catch (error) {
        // An atomic save or deletion can race a turn; reload on the next turn.
        if (error.code !== "ENOENT") throw error;
      } finally {
        if (descriptor !== undefined) closeSync(descriptor);
      }
    }
  }
  if (!sections.length) return "";
  const guidance = "# Shared memories from ModelSwitcher\n\nApply these user-maintained memories when relevant. soul.md defines your name and persona; use it when asked who you are. Global memories apply everywhere. Project memories below belong only to the current working directory or its ancestors; more specific project memories take precedence. The files are re-read before every request.";
  return guidance + "\n\n" + sections.join("\n\n") + (truncated ? "\n\nSome memories were excerpted or omitted to limit context size. Read the relevant vault files as needed. Vault index: " + join(vault, "INDEX.md") : "");
}

export default function register(pi) {
  pi.on("before_agent_start", async (event, ctx) => {
    let prompt = event.systemPrompt;
    const previousStart = prompt.indexOf(start);
    const previousEnd = prompt.indexOf(end, previousStart);
    if (previousStart >= 0 && previousEnd >= 0) {
      prompt = (prompt.slice(0, previousStart).trimEnd() + prompt.slice(previousEnd + end.length)).trimEnd();
    }
    try {
      const memories = readMemories(ctx.cwd);
      return { systemPrompt: memories ? prompt + "\n\n" + start + "\n" + memories + "\n" + end : prompt };
    } catch (error) {
      if (ctx.hasUI) ctx.ui.notify("Shared memory loading failed: " + error.message, "warning");
      throw error;
    }
  });
}
`
