// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateOpenAI():Promise<main.AppState>;

export function ActivateProfile(arg1:string):Promise<main.AppState>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ChooseChatGPTPath():Promise<main.AppState>;

export function DeleteProfile(arg1:string):Promise<main.AppState>;

export function DeleteSkill(arg1:string):Promise<Array<main.SkillInfo>>;

export function FetchModels(arg1:main.ProfileInput):Promise<Array<main.Model>>;

export function InstallSkill(arg1:string):Promise<Array<main.SkillInfo>>;

export function ListSkillCatalog():Promise<Array<main.SkillCatalogItem>>;

export function ListSkills():Promise<Array<main.SkillInfo>>;

export function LoadSkillsState():Promise<main.SkillsState>;

export function LoadState():Promise<main.AppState>;

export function OpenCodexDirectory():Promise<void>;

export function OpenConfigFolder():Promise<void>;

export function ReadConfigText():Promise<string>;

export function SaveProfile(arg1:main.ProfileInput):Promise<main.AppState>;

export function SetChatGPTPath(arg1:string):Promise<main.AppState>;

export function StartUpdate():Promise<main.UpdateInfo>;

export function WriteConfigText(arg1:string):Promise<void>;
