// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateOpenAI() {
  return window['go']['main']['App']['ActivateOpenAI']();
}

export function ActivateProfile(arg1) {
  return window['go']['main']['App']['ActivateProfile'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ChooseChatGPTPath() {
  return window['go']['main']['App']['ChooseChatGPTPath']();
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function FetchModels(arg1) {
  return window['go']['main']['App']['FetchModels'](arg1);
}

export function InstallSkill(arg1) {
  return window['go']['main']['App']['InstallSkill'](arg1);
}

export function ListSkillCatalog() {
  return window['go']['main']['App']['ListSkillCatalog']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function LoadSkillsState() {
  return window['go']['main']['App']['LoadSkillsState']();
}

export function LoadState() {
  return window['go']['main']['App']['LoadState']();
}

export function OpenCodexDirectory() {
  return window['go']['main']['App']['OpenCodexDirectory']();
}

export function OpenConfigFolder() {
  return window['go']['main']['App']['OpenConfigFolder']();
}

export function ReadConfigText() {
  return window['go']['main']['App']['ReadConfigText']();
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SetChatGPTPath(arg1) {
  return window['go']['main']['App']['SetChatGPTPath'](arg1);
}

export function StartUpdate() {
  return window['go']['main']['App']['StartUpdate']();
}

export function WriteConfigText(arg1) {
  return window['go']['main']['App']['WriteConfigText'](arg1);
}
